# /data/db/metadata_jav_settings.yaml

# JAV 메타데이터 고급 설정
# 이 파일에서 파싱 규칙 등 다양한 설정을 관리할 수 있습니다.

# JAV 파일명 파싱 규칙
jav_parsing_rules:
  # 통합 JAV 파일명 파싱 규칙
  # 이 규칙들은 파일처리시 파일명이나 메타 사이트 등에서 품번을 파싱하기 위해 사용됩니다.
  # 각 섹션의 규칙은 위에서부터 순서대로 적용됩니다.
  # 참고: #으로 시작하는 줄은 주석으로 처리되어 무시됩니다.

  # 범용 규칙 (모든 모드에서 특수 규칙보다 나중에 시도됨)
  generic_rules:
    - '.*?\d*([a-z]+)-(\d+)(?=[^\d]|\b) => {0}|{1}'
    - '.*?\b([0-9a-z]+)-(\d+)(?=[^\d]|\b) => {0}|{1}'
    - '.*?\d*([a-z]+)-?(\d+)(?=[^\d]|\b) => {0}|{1}'
    - '.*?\b([0-9a-z]*[a-z]+)-?(\d+)(?=[^\d]|\b) => {0}|{1}'

  # 아래 특수 규칙들은 범용 규칙보다 우선하며, 복잡한 예외 케이스를 정규식으로 직접 처리합니다.
  # 캡쳐 그룹의 개수나 문자/숫자의 조합 등의 제한도 없지만, 반드시 파이프(|)로 구분된 2개의 파트로 나뉘어야 합니다.
  # 형식: 정규식 패턴 => 레이블네임 템플릿|레이블넘버 템플릿
  # 예시 (HEYZO): .*?(heyzo)[-_\s]?(\d{4}) => {0}|{1}
  # - 위 규칙은 heyzo 2681, heyzo-2681 같은 품번을 레이블: HEYZO, 숫자: 2681로 파싱합니다.

  # Censored 전용 특수 규칙
  censored_special_rules:
    # 3DSVR (예: [VCB] 13dsvr-039.mkv -> 3DSVR-039)
    - '.*?(3dsvr)[-_]?(\d+)(?=[^\d]|\b) => {0}|{1}'

    # 741M...-G... (예: 741m683-g02.mp4 -> 741M683-G02)
    - '.*?(?<![a-z0-9])(741[a-z]\d{3})[-_]?(g\d{2,})(?=[^\d]|\b) => {0}|{1}'

    # T28/T38 (예: [Subs] 1t28-635.mkv -> T28-635)
    - '.*?(?<![a-z])(t)[-_]?(28|38)[-_]?(\d+)(?=[^\d]|\b) => {0}{1}|{2}'

    # ID (예: 55id16045 -> 16ID-045)
    - '.*?(\d{2})?(id)[-_]?([1-9]\d|\d[1-9])(\d{3})(?=[^\d]|\b) => {2}{1}|{3}'

    # CPZ...-H... (예: [MyDir] 1cpz69h004 -> CPZ69-H004)
    - '.*?(?<![a-z])(cpz\d{2})[-_]?([a-z]\d+)(?=[^\d]|\b) => {0}|{1}'

    # GAREA (예: G-AREA-123 -> GAREA-123)
    - '.*?(?<![a-z])(g)[-_](area)[-_]?(\d+)(?=[^\d]|\b) => {0}{1}|{2}'

    # SCUTE (예: S-CUTE-1234 -> SCUTE-1234)
    - '.*?(?<![a-z])(s)[-_](cute)[-_]?(\d+)(?=[^\d]|\b) => {0}{1}|{2}'

    # MBRXX (예: MBR-AA-123 -> MBRAA-123)
    - '.*?(?<![a-z])(mar|mbr|mmr)[-_]([a-z]{2})[-_]?(\d+)(?=[^\d]|\b) => {0}{1}|{2}'

    # TOKYO (예: TOKYO247-123 -> TOKYO-123)
    - '.*?(?<![a-z])(tokyo)247[-_]?(\d+)(?=[^\d]|\b) => {0}|{1}'

    # 레이블 앞 3자리 숫자 유지
    - '.*?(\d{3})(ap|good|san|ten)[-_]?(\d+)(?=[^\d]|\b) => {0}{1}|{2}'

    # 레이블 앞 2자리 숫자 유지
    - '.*?(\d{2})(ap|id|ntrd|san|sora|sw|ten)[-_]?(\d{3,4})(?=[^\d]|\b) => {0}{1}|{2}'

  # 3. Uncensored 전용 특수 규칙
  uncensored_special_rules:
    # 1pondo
    - '.*?(?<![0-9])(1pon|1pondo)[-_\s]?(\d{6})[-_](\d{2,3})(?=[^\d]|\b).*? => 1pon|{1}_{2}'
    - '.*?(?<![0-9])(\d{6})[-_](\d{2,3})[-_\s]?(1pon|1pondo)\b.*? => 1pon|{0}_{1}'

    # 10musume
    - '.*?(?<![0-9])(10mu|10musume)[-_\s]?(\d{6})[-_](\d{2,3})(?=[^\d]|\b).*? => 10mu|{1}_{2}'
    - '.*?(?<![0-9])(\d{6})[-_](\d{2,3})[-_\s]?(10mu|10musume)\b.*? => 10mu|{0}_{1}'

    # Carib
    - '.*?(?<![a-z])carib(bean)?(com)?[-_\s]?(\d{6})[-_]?(\d{2,3})(?=[^\d]|\b).*? => carib|{2}-{3}'
    - '.*?(?<![0-9])(\d{6})[-_](\d{2,3})[-_\s]?carib(bean)?(com)?\b.*? => carib|{0}-{1}'

    # FC2
    - '.*?(?<![a-z])(fc2)[-_\s]?(ppv)?[-_\s]?(\d{5,7})(?=[^\d]|\b).*? => {0}|{2}'

    # HEYZO
    - '.*?(?<![a-z])(heyzo)[-_\s]?(\d{4})(?=[^\d]|\b).*? => {0}|{1}'

    ##### 아래는 기타 레이블 규칙 #####
    # C0930
    - '.*?(?<![a-z])(c0930)[-_]([a-z]+\d+)(?=[^\d]|\b).*? => {0}|{1}'
    # 123456-012-LABEL
    - '.*?(?<![0-9])(\d{6})[-_](\d{2,3})[-_\s]?([a-z]+)\b.*? => {2}|{0}-{1}'

    # Uncensored용 우선 범용 규칙
    - '.*?\b([0-9a-z]+)-(\d+)(?=[^\d]|\b) => {0}|{1}'
