# /data/db/jav_custom_settings.yaml

# JAV 메타데이터/파일처리 고급 설정
# 이 파일에서 파싱 규칙 등 다양한 설정을 관리할 수 있습니다.
# #으로 시작하는 줄은 주석으로 처리되어 무시됩니다.

# -------------------------------------------------------------------
# [필수] JAV 파일명 파싱 규칙
# -------------------------------------------------------------------
# 이 규칙들은 파일처리/메타데이터에서 품번을 파싱하기 위해 사용됩니다.
# 각 섹션의 패턴(정규표현식)과 매칭 규칙은 위에서부터 순서대로 시도됩니다.

# 캡쳐 그룹의 개수나 문자/숫자 조합 등의 제한은 없지만, 반드시 파이프(|)로 구분된 2개의 파트로 나뉘어야 합니다.
# 캡쳐 그룹의 인덱스는 {0}부터 시작합니다.
# 형식: 정규식 패턴 => 레이블 네임|넘버 파트
# 예시 (HEYZO): .*?(heyzo)[-_\s]?(\d{4}) => {0}|{1}
# - 위 규칙은 heyzo 2681, heyzo-2681 같은 품번을 레이블: HEYZO, 숫자: 2681로 파싱합니다.
jav_parsing_rules:
  # 범용 규칙 (모든 모드에서 특수 규칙보다 나중에 시도됨)
  # 특수 규칙에 해당되지 않는 일반적인 품번 형태(Fallback)
  generic_rules:
    - '.*?\d*([a-z]+)-(\d+)(?=[^\d]|\b) => {0}|{1}'
    - '.*?\d*([a-z]+)-?(\d+)(?=[^\d]|\b) => {0}|{1}'
    - '.*?\b([0-9a-z]*[a-z]+)-(\d+)(?=[^\d]|\b) => {0}|{1}'
    - '.*?\b([0-9a-z]*[a-z]+)-?(\d+)(?=[^\d]|\b) => {0}|{1}'

  # 아래 특수 규칙들은 범용 규칙보다 우선하며, 복잡한 예외 케이스를 정규식으로 직접 처리합니다.
  # Censored 전용 특수 규칙
  censored_special_rules:
    # 3DSVR (예: [VCB] 13dsvr-039.mkv -> 3DSVR-039)
    - '.*?(3dsvr)[-_]?(\d+)(?=[^\d]|\b) => {0}|{1}'

    # 741M...-G... (예: 741m683-g02.mp4 -> 741M683-G02)
    - '.*?(?<![a-z0-9])(741[a-z]\d{3})[-_]?(g\d{2,})(?=[^\d]|\b) => {0}|{1}'

    # T28/T38 (예: [Subs] 1t28-635.mkv -> T28-635)
    - '.*?(?<![a-z])(t)[-_]?(28|38)[-_]?(\d+)(?=[^\d]|\b) => {0}{1}|{2}'

    # ID (예: 55id16045 -> 16ID-045)
    - '.*?(\d{2})?(id)[-_]?([1-9]\d|\d[1-9])(\d{3})(?=[^\d]|\b) => {2}{1}|{3}'

    # CPZ...-H... (예: [MyDir] 1cpz69h004 -> CPZ69-H004)
    - '.*?(?<![a-z])(cpz\d{2})[-_]?([a-z]\d+)(?=[^\d]|\b) => {0}|{1}'

    # GAREA (예: G-AREA-123 -> GAREA-123)
    - '.*?(?<![a-z])(g)[-_](area)[-_]?(\d+)(?=[^\d]|\b) => {0}{1}|{2}'

    # SCUTE (예: S-CUTE-1234 -> SCUTE-1234)
    - '.*?(?<![a-z])(s)[-_](cute)[-_]?(\d+)(?=[^\d]|\b) => {0}{1}|{2}'

    # MBRXX (예: MBR-AA-123 -> MBRAA-123)
    - '.*?(?<![a-z])(mar|mbr|mmr)[-_]([a-z]{2})[-_]?(\d+)(?=[^\d]|\b) => {0}{1}|{2}'

    # TOKYO (예: TOKYO247-123 -> TOKYO-123)
    - '.*?(?<![a-z])(tokyo)247[-_]?(\d+)(?=[^\d]|\b) => {0}|{1}'

    # WVR
    - '.*?(?<![a-z])(wvr)0([1-9])[-_]?([a-z]?\d+)\b => {0}{1}|{2}|{0}0{1}'
    - '.*?(?<![a-z])(wvr)0*([1-9])[-_]?([a-z]?\d+)\b => {0}{1}|{2}|{0}{1}'

    # YPP
    - '.*?([0-9]{3}ypp)[-_]?(\d+)(?=[^\d]|\b) => {0}|{1}'

    # 레이블 앞 3자리 숫자 유지
    - '.*?(?<![0-9])(\d{3})(ap|good|san|ten)[-_]?(\d+)(?=[^\d]|\b) => {0}{1}|{2}'

    # 레이블 앞 2자리 숫자 유지
    - '.*?(?<![0-9])(\d{2})(ap|id|ntrd|san|sora|sw|ten)[-_]?(\d+)(?=[^\d]|\b) => {0}{1}|{2}'

    # 레이블 앞 1자리 숫자 유지(검색에만)
    - '.*?(?<![0-9])(\d{1})(sw)[-_]?(\d+)(?=[^\d]|\b) => {1}|{2}|{0}{1}'


  # 3. Uncensored 전용 특수 규칙
  uncensored_special_rules:
    # 1pondo
    - '.*?(?<![0-9])(1pon|1pondo)[-_\s]?(\d{6})[-_](\d{2,3})(?=[^\d]|\b).*? => 1pon|{1}_{2}'
    - '.*?(?<![0-9])(\d{6})[-_](\d{2,3})[-_\s]?(1pon|1pondo)\b.*? => 1pon|{0}_{1}'

    # 10musume
    - '.*?(?<![0-9])(10mu|10musume)[-_\s]?(\d{6})[-_](\d{2,3})(?=[^\d]|\b).*? => 10mu|{1}_{2}'
    - '.*?(?<![0-9])(\d{6})[-_](\d{2,3})[-_\s]?(10mu|10musume)\b.*? => 10mu|{0}_{1}'

    # Carib
    - '.*?(?<![a-z])carib(bean)?(com)?[-_\s]?(\d{6})[-_]?(\d{2,3})(?=[^\d]|\b).*? => carib|{2}-{3}'
    - '.*?(?<![0-9])(\d{6})[-_](\d{2,3})[-_\s]?carib(bean)?(com)?\b.*? => carib|{0}-{1}'

    # FC2
    - '.*?(?<![a-z])(fc2)[-_\s]?(ppv)?[-_\s]?(\d{5,7})(?=[^\d]|\b).*? => {0}|{2}'

    # HEYZO
    - '.*?(?<![a-z])(heyzo)[-_\s]?(\d{4})(?=[^\d]|\b).*? => {0}|{1}'

    ### 기타 레이블 규칙 ###
    # C0930
    - '.*?(?<![a-z])(c0930)[-_]([a-z]+\d+)(?=[^\d]|\b).*? => {0}|{1}'

    # 이미 처리된 파일
    - '^([a-z0-9]+)-((?:\d{6}[-_]\d{2,3})|(?:[a-z]*\d+))(?=[^\d]|\b).*? => {0}|{1}'

    # 123456-012-LABEL
    - '.*?(?<![0-9])(\d{6})[-_](\d{2,3})[-_\s]?([a-z]+)\b.*? => {2}|{0}-{1}'

    ### Uncensored용 우선 범용 규칙 ###
    - '.*?\b([0-9a-z]+)-(\d+)(?=[^\d]|\b) => {0}|{1}'


# [고급] 설정은 선택사항이며 옵션 세부설정 또는 특수기능을 위한 부분입니다.
# 설정이 없으면 기본값을 따릅니다.

# -----------------------------------------------------------------
# [고급] JAV 이미지 처리 관련 고급 설정
# -----------------------------------------------------------------
jav_image_settings:
  # 이미지 해시 비교 시 사용되는 임계값 (낮을수록 엄격함)
  # - hq_poster_threshold_strict: 단순 비교(is_hq_poster) 시 사용. 텍스트까지 거의 일치해야 할 때. (기본값: 10)
  # - hq_poster_threshold_normal: 확장 비교(has_hq_poster) 시 사용. 전처리 후 비교하므로 약간 관대함. (기본값: 30)
  hq_poster_threshold_strict: 10
  hq_poster_threshold_normal: 30


# -------------------------------------------------------------------
# [고급] 기타 설정
# -------------------------------------------------------------------
misc_settings:
  # --- 중복 파일 판단 기준 ---
  # 사용 가능한 옵션:
  #   - "strict": 파일명과 파일 크기가 모두 동일해야 중복으로 처리합니다. (가장 엄격)
  #   - "flexible": 파일명이 같거나, 또는 파일 크기가 같으면 중복으로 처리합니다. (강력한 중복 제거, 기본값)
  #   - "filename_only": 파일명이 동일한 경우 중복으로 처리합니다(파일 크기 체크 X).
  duplicate_check_method: flexible

  # 이미 파일처리(원본파일명 보존)된 형식인지 확인용 패턴.
  # 이 패턴과 일치하는 파일은 파일명 변경을 건너뜁니다.
  already_processed_pattern: '^[a-zA-Z0-9]+-[a-zA-Z0-9-_]+(\s\[.*\](?:cd\d+)?)$'

  # 숫자가 앞에 오는 레이블의 경우 {label_1}은 기본적으로 숫자를 무시합니다.
  # 숫자를 허용하고 '09' 폴더에 넣을 레이블을 지정해줍니다.
  allowed_numeric_labels: '^(741|1pon|10mu).*?'

  # PLEX MATE 스캔('On'일 때) 세부설정
  # True: 메타 매칭 결과가 없어도 스캔
  # False: 메타 매칭 결과가 없으면 스캔 생략
  scan_with_no_meta: True

  # 메타 검색에 사용할 사이트와 통과 기준 점수를 지정할 수 있습니다(Censored 전용 설정).
  # 이 설정이 없으면 설정 UI의 '정상 매칭 판단에 DMM+MGS만 사용' 옵션에 따르며, 통과 점수는 95점이 됩니다.
  # 메타검색에사용할사이트:
  #   - 사이트: "dmm"
  #     점수: 95
  #   - 사이트: "mgstage"
  #     점수: 95
  #   - 사이트: "javdb"
  #     점수: 80
  #   - 사이트: "jav321"
  #     점수: 80
  #   - 사이트: "javbus"
  #     점수: 60


# -------------------------------------------------------------------
# [고급] ffprobe를 이용한 파일명 포맷팅
# -------------------------------------------------------------------
# '미디어 정보 추가' 옵션의 세부 설정입니다.
filename_with_media_info:
  # ffprobe 실행 파일의 절대 경로입니다.
  ffprobe_path: /usr/bin/ffprobe

  # --- 분할 파일 세트의 파일명 생성을 위한 허용 오차 ---
  # 분할 파일 세트로 식별된 파일들의 미디어 정보를 비교하여,
  # 아래 허용 오차 내에 있으면 '첫 번째 파일(cd1)'의 값을 대표로 사용하여
  # 모든 파트의 파일명을 동일하게 만듭니다.
  # 허용 오차를 벗어나는 정보는 파일명에서 제외됩니다.
  tolerance:
    # 오디오 비트레이트 허용 오차 (단위: kbps)
    audio_bitrate: 5
    # 프레임레이트(fps) 허용 오차
    fps: 0.01

  # --- 표준 프레임레이트 값 ---
  # ffprobe로 추출된 fps 값이 아래 목록의 값과 허용 오차 내에 있을 경우,
  # 해당 표준 값으로 보정되어 파일명에 사용됩니다. (예: 59.941 -> 59.94)
  standard_fps_values: [23.976, 24, 25, 29.97, 30, 59.94, 60]

    # --- 해상도 표준화 규칙 ---
  # height 값을 기준으로 해상도 태그를 결정합니다. 위에서부터 순서대로 검사합니다.
  resolution_tiers:
    - { min_height: 4000, max_height: 6000, tag: "8K" }
    - { min_height: 2880, max_height: 4000, tag: "6K" }
    - { min_height: 1600, max_height: 2880, tag: "4K" }
    - { min_height: 1200, max_height: 1600, tag: "3K" }
    - { min_height: 900,  max_height: 1200, tag: "FHD" }
    - { min_height: 600,  max_height: 900,  tag: "HD" }
    - { min_height: 0,    max_height: 600,  tag: "SD" }

  # --- 미디어 정보 템플릿 ---
  # 파일명에 추가될 미디어 정보 부분의 형식을 정의합니다.
  # {{...}} 구문: 덩어리(chunk). 중괄호 안의 모든 변수가 유효할 때만 덩어리 전체가 출력됩니다.
  #              예를 들어, {a_bitrate} 값이 없으면 {{-{a_bitrate}kbps}} 전체가 생략됩니다.
  #
  # 사용 가능한 변수:
  # {res_tag}, {width}, {height}, {v_codec}, {a_codec}, {a_bitrate}, {fps}, {tag_title}
  media_info_template: "[[{res_tag}]][[.{v_codec}]][[.{fps}fps]][[.{a_codec}]][[-{a_bitrate}kbps]][[.{tag_title}]]"

  # true로 설정하면, 아래 두 패턴을 사용하여 이미 처리된 파일명을 동적으로 수정합니다.
  enable_reprocessing: false

  # 이미 처리된 형식(미디어 정보 포함) 파일명을 식별하여 재처리를 건너뛰기 위한 정규식입니다.
  reprocess_skip_pattern: '\[(SD|HD|FHD|3K|4K|6K|8K)\.(H264|H265|HEVC|AV1|VP9|AVI|MPEG)'

  # 이미 처리된 형식(미디어 정보 없는) 파일명에 미디어 정보를 동적으로 삽입하기 위한 정규식입니다.
  # 그룹1: 품번, 그룹2: ' [', 그룹3: '원본정보...]'
  reprocess_insert_pattern: '^([a-zA-Z0-9]+-[a-zA-Z0-9-_]+)(\s\[)(.*\](?:cd\d+)?)$'


# -------------------------------------------------------------------
# [고급] 경로 이동 커스텀 설정: 파일명 패턴, 레이블
# -------------------------------------------------------------------
# 메타 검색 성공 시, 파일의 레이블이 아래 규칙과 일치하면
# '메타매칭시이동폴더' 대신 여기에 지정된 '경로'로 파일을 이동시킵니다.
# '경로'를 지정하지 않으면 기본 경로 설정을 따릅니다.
# '폴더포맷'은 지정하지 않으면 기본 폴더 구조 설정을 따릅니다.
# '레이블'과 '파일명패턴'은 정규표현식을 사용하고, 동시에 사용할 수 있습니다.
# '모듈': censored / uncensored / all(생략시 디폴트)
# '메타실패시강제적용': True/False (True로 설정시 실패경로가 아닌 타겟경로로 이동)
# 규칙의 각 항목은 중복시 아래쪽에 있는 것을 우선으로 병합됩니다.
# 개별 설정과 공통 설정을 별도로 작성할 수 있습니다.
# 폴더 구조 템플릿:
# {label_1}: 레이블 첫글자. 숫자의 경우 09 / {label}: 레이블 명 / {num_X_Y}: Y 자릿수 패딩 중 앞 3자리 숫자 폴더 생성
# {year}: MMDDYY 품번 숫자에서 연도를 추출하여 20YY 폴더 생성 / {yymm}: MMDDYY 품번 숫자에서 연월 추출해 YYMM 생성. ex) 083125 -> 2508
# {code}: 품번 / 기타: {year}, {studio}, {label_lower}, {code_lower}, {studio_lower}, {actor}, {actor_2}, {actor_3}
meta_custom_path:
  enable: True
  규칙:
    - 이름: uncen_year4
      모듈: uncensored
      레이블: '(1pon|10mu|carib)'  # 정규식 패턴
      폴더포맷: '{label}/{year4}'  # 템플릿
    - 이름: uncen_num_3_7
      모듈: uncensored
      레이블: '(fc2)'
      폴더포맷: '{label}/{num_3_7}'
    - 이름: uncen_num_2_4
      모듈: uncensored
      레이블: '(heyzo)'
      폴더포맷: '{label}/{num_2_4}'
    #- 이름: uncen_meta_path
    #  모듈: uncensored
    #  레이블: '(1pon|10mu|carib|fc2|heyzo)'
    #  경로: '/PATH/TO/JAV/UNCEN/META'

    # ex)
    #- 이름: CenManiacLabel
    #  모듈: censored
    #  레이블: |
    #    (
    #      13sw|59ten|143ten|741h057|741m635|741m649|741p015|741p016|741p017|741p020|741p023|
    #      abba|abd|abnomal|acz|aczd|add|advo|aed|aeg|agd|agr|ahshiro|aldn|alx|amtr|anb|annd|anz|aran|ast|atena|aukb|aukg|auks|aukt|av|avgl|avsa|awd|
    #      ...
    #    )
    #  경로: '/PATH/TO/JAV/CEN/MANIAC'


# -------------------------------------------------------------------
# [고급] 자막영상 관리 경로로 이동
# -------------------------------------------------------------------
# 기본 라이브러리 외 경로에 따로 자막 영상을 관리하는 경우 이용할 수 있는 기능입니다.
# 이동 라이브러리와 매칭되는 폴더구조에서 해당 품번에 자막파일이 있을 경우 그 폴더로 이동합니다.
# 파일명 내에 내장자막키워드가 포함된 경우에도 자막관리 경로로 이동합니다
# subbed_path:
#   처리활성화: False
#   자막파일확장자: ass ssa idx sub sup smi srt ttml vtt
#   내장자막키워드: 자막 korsub
#   규칙:
#     - 이름: cen_subbed
#       모듈: censored
#       이동제외패턴: '(decen(sored)?|javplayer|mosaic|no[-_ ]?mask|uncen(sored)?|모자이크)'
#       경로: "/PATH/TO/JAV/CEN/SUBBED"
#     - 이름: uncen_subbed
#       모듈: uncensored
#       경로: "/PATH/TO/JAV/UNCEN/SUBBED"
